### PR TITLE
updated: add band property to Attendee band plugin mixin

### PR DESCRIPTION
**Pull request by binary1230**
implement 'band' property for Attendee in order to tell if this attendee is associated with a band

useful for a bunch of stuff, we're going to use it in magstock plugin to tell it that bands get free food.

### CODE REVIEW

**Comment by kitsuta** [comment]
I'm not a fan of having a non-event plugin customized to an event plugin's needs. See https://github.com/magfest/magstock/pull/75/files/206c6981de5060d7b0ed34fdec079663646a0ed6#r66327466 for more rambling on it.

**Comment by kitsuta** [comment]
I like this change. I might prefer to name this property `has_band` or `in_band` for the sake of consistency (we use the verb structure a lot elsewhere) and brevity ('associated' is tricky to write out!), but I'm good with this either way.

**Comment by kitsuta** [comment]
Oh, come to think of it, we can shorten this property to just `band` because it'll have the `attendee` context. So `attendee.band`.

**Comment by binary1230** [comment]
shortened to just 'band'

**Comment by binary1230** [comment]
flipped the abstraction around per Vicki's original comments

**Pull request merged**
